[package]
name = "ziggy"
version = "0.4.4"
edition = "2021"
license = "Apache-2.0"
description = "A multi-fuzzer management utility for all of your Rust fuzzing needs 🧑‍🎤"
repository = "https://github.com/srlabs/ziggy/"

[workspace]
members = [
    ".",
    "examples/arbitrary",
    "examples/url",
    "examples/with_lazy_static",
]

[dependencies]
clap = { version = "4.2.7", features = ["cargo", "derive"], optional = true }
console = { version = "0.15.5", optional = true }
glob = { version = "0.3.1", optional = true }
toml = { version = "0.7.3", optional = true }
anyhow = { version = "1.0.71", optional = true }
afl = { version = "0.12.17", default-features = false, optional = true }
honggfuzz = { version = "0.5.55", optional = true }
serde_json = { version = "1.0.96", optional = true }
log = { version = "0.4.17", optional = true }
env_logger = { version = "0.10.0", optional = true }

[features]
default = ["cli"]
cli = ["clap", "console", "glob", "toml", "anyhow", "serde_json", "log", "env_logger"]
reset_lazy_static = ["afl?/reset_lazy_static"]
