[package]
name = "with-lazy-static"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
ziggy = { path = "../../", default-features = false, features = ["reset_lazy_static"] }

[patch.crates-io]
lazy_static = { git = "https://github.com/rust-fuzz/resettable-lazy-static.rs" }